name: "Um pipeline para meu Hello World"
on: push

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions-a
        with: 
          MY_NAME: "Luiz Gadelha"